# Generated by Django 2.1 on 2018-10-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(null=True, to='med_management.Medication'),
        ),
    ]
