# Generated by Django 2.1 on 2018-10-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0002_auto_20181012_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, to='med_management.Medication'),
        ),
    ]
