# Generated by Django 2.1 on 2018-10-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0004_auto_20181016_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='patients',
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, to='med_management.Medication'),
        ),
    ]
