# Generated by Django 2.1 on 2018-10-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0005_auto_20181016_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='med_management.Medication')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='medications',
            field=models.ManyToManyField(blank=True, to='med_management.Prescription'),
        ),
    ]
