# Generated by Django 2.1 on 2018-10-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0006_auto_20181016_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='medications',
            new_name='prescriptions',
        ),
    ]
