# Generated by Django 2.1 on 2018-10-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med_management', '0007_auto_20181016_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='med_management.Patient'),
            preserve_default=False,
        ),
    ]
